# .github/workflows/sync-upstream-tags.yml
name: Sync upstream tags

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  sync-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Sync tags from upstream
        env:
          TOKEN: ${{ secrets.SYNC_TAGS_TOKEN }}
        run: |
          git remote add upstream https://github.com/apple/swift-crypto.git
          git fetch upstream --tags

          git remote set-url origin https://x-access-token:${TOKEN}@github.com/bytehubio/swift-crypto.git
          git push origin --tags
